### ISSUE TITLE
TCP connection error 

### ISSUE THREAD

**Issue by sreesms** [Dobot-Arm/CR5_ROS#1]
When I launch the command :
roslaunch dobot_bringup bringup.launch robot_ip:=192.168.5.1

I am getting the error as  [ERROR] [1635400577.535037528]: tcp recv error : 192.168.5.1:30003 connect : Connection refused.

The ping is working fine. How to solve this issue?

**Comment by sreesms** [comment]
The error was solved when the firmware of Dobot upgraded to 3.5.1.10

**Comment by ou-ais** [comment]
I have been meeting the same problem. But I don't know what is the firmware mean. I connect the Robot CR5 with linux directly by the TCP/IP. Could you tell me how did you adress the trouble. Thank you.

**Comment by sreesms** [comment]
You can find the details in this link: [https://www.dobot.cc/video/how-to-update-dobot-firmware.html](url)

**Comment by iameijaz** [comment]
How can we check the firmware version? Also, this problem was resolved by changing some IP Settings in LAN for Ubuntu.
